#!/bin/bash
install_path=$HOME"/.themes/numix-gtk-theme/"
source_dir=$HOME"/numix-resources/metacity-1"
target_dir=$install_path"metacity-1/"

cd $source_dir;
for i in *; 
do inkscape $i --export-png=`echo $target_dir$i | sed -e 's/svg$/png/'`; 
echo $target_dir$i;
done

